# -*- coding: utf-8 -*-
"""LMS_ME_Bootcamp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMXIN5SLUUj2kpyrKmvLxCJZ9XOJgDm3
"""

#Merve Enbiyaoğlu LMS
class Library:
    def __init__(self, db='books.txt'):
        self.db = db
        self.file = open(self.db, 'a+')

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        book_lines = self.file.read().splitlines()
        for line in book_lines:
            book_info = line.split(',')
            print(f"Book: {book_info[0]}, Author: {book_info[1]}")

    def add_book(self):
        title = input("Enter the book title: ")
        author = input("Enter the author: ")
        release_year = input("Enter the release year: ")
        num_pages = input("Enter the number of pages: ")

        book_info = f"{title},{author},{release_year},{num_pages}\n"
        self.file.write(book_info)
        print(f"Book '{title}' added successfully!")

    def remove_book(self):
        title_remove = input("Enter the book title to remove: ")

        self.file.seek(0)
        book_lines = self.file.read().splitlines()

        new_book_lines = [line for line in book_lines if title_remove not in line]

        self.file.truncate(0)
        self.file.seek(0)

        for line in new_book_lines:
            self.file.write(line + '\n')

        print(f"Book '{title_remove}' removed successfully!")

lib = Library()

while True:
    print("\n*** MENU ***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("q) Exit")

    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        lib.list_books()
    elif choice == '2':
        lib.add_book()
    elif choice == '3':
        lib.remove_book()
    elif choice == 'q':
        break
    else:
        print("Please enter a number between 1 and 3 or q.")